language: node_js

node_js:
  - "0.10"

install:
  - npm install spm@ninja coveralls mocha

before_script:
  - npm install
  - node_modules/spm/bin/spm-install

script:
  - node_modules/.bin/mocha -R spec tests/versioning-spec.js
  - node_modules/spm/bin/spm-test

after_success:
  - node_modules/spm/bin/spm-test --coveralls | node_modules/.bin/coveralls
